# Compilation
FROM node:16 AS angular
WORKDIR /code
COPY frontend/package.json /code/
COPY frontend/src /code/src
RUN npm install
RUN npm run ng build -- --prod --base-href=/new/
RUN ls -l



FROM maven:3.6.3-openjdk-17 as builder
WORKDIR /project
COPY backend/nutricion/pom.xml /project/
COPY backend/nutricion/src /project/src
COPY --from=angular /code/dist/frontend /project/src/main/resources/static/new
RUN mvn package


FROM openjdk:17
WORKDIR /usr/src/app/
COPY --from=builder /project/target/*.jar /usr/src/app/
EXPOSE 8443
CMD [ "java", "-jar", "nutricion-0.0.1-SNAPSHOT.jar" ]

