version: "3.9"
services:
  web:
    image: adroius/codeurjc-daw-2022-23-webapp10:v.1
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/TheSmartWay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0.24
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TheSmartWay
    ports:
      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
