version: "3.9"
services:
  web:
    image: adroius/codeurjc-daw-2022-23-webapp10
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/TheSmartWay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0.24
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "5432:5432"
    volumes:
      - mysql-data:/var/lib/mysql

  volumes:
      mysql-data:
        external:true